# Site settings
title: Engine Room
description: それでもWindowsで開発するブログ
copyright: (C) 2015 Junya Onishi
baseurl: ""
url: "http://junyaonishi.github.io/"

#profile
author: Junya Onishi
email: j-onishi@kk-ty.co.jp
aboutMe: 株式会社ティー・ワイに所属するフロント寄りWEBエンジニア<br>今日も今日とてWindowsで開発する。<br>Windowsだけはそろそろ辛い。
twitter_username: JugnautOnishi
github_username:  JunyaOnishi

# Build settings
markdown: kramdown
