# Site settings
title: Engine Room |それでもWindowsで開発するブログ
email: j-onishi@kk-ty.co.jp
description: どうにかこうにか頑張ってWindowで開発するブログ
copyright: (C) 2015 Junya Onishi
baseurl: ""
url: "http://JunyaOnishi.github.io/"
twitter_username: JugnautOnishi
github_username:  JunyaOnishi

# Build settings
markdown: kramdown
